### ISSUE TITLE
[TODO]开发一个可以在pypi上安装的python包

### ISSUE THREAD

**Issue by lai-bluejay** [MeiK2333/QQMusicAPI#7]
周末想帮忙把这个包改成可以直接在pypi上进行安装的包，方便进行调用和使用~~

到时候给你提pr哦

**Comment by MeiK-h** [comment]
好的好的，十分感谢～

**Comment by lai-bluejay** [comment]
#8 已经提交。

**Comment by MeiK-h** [comment]
提交啦，https://pypi.org/project/qqmusic-api/，非常感谢～
